#
# Service to send ScriptControl commands to CarMaker GUI
#

# general type of command
string type

# message to be evaluated
string msg

# additional data, e.g. command arguments, ...
string data

---

# result of triggered service
int32 res

# informational, e.g. for error messages
string msg
