Header header

#COG
CarVelocity velocity
geometry_msgs/Point acceleration

#Velocity in X
float32 frontLeftVX
float32 frontRightVX
float32 rearLeftVX
float32 rearRightVX

#Velocity in Y
float32 frontLeftVY
float32 frontRightVY
float32 rearLeftVY
float32 rearRightVY

#Slip ratio
float32 frontLeftSR
float32 frontRightSR
float32 rearLeftSR
float32 rearRightSR

#Slip angle
float32 frontLeftSA
float32 frontRightSA
float32 rearLeftSA
float32 rearRightSA