# informational, e.g. name of triggering node
string message

---

# indicate successful run of triggered service
bool success

# default cycle time in ms
int32 cycletime

# informational, e.g. for error messages
string message
